### ISSUE TITLE
Can't get the neuroweb repo working. 

### ISSUE THREAD

**Issue by bdepyzy** [OriginTrail/neuroweb#113]
While running `examples/demo.py`, the node initially works but then encounters a JSON parse error. The error occurs during node info processing, suggesting an incomplete or malformed JSON response.

## Error Details
```json
{
    "jsonrpc": "2.0",
    "id": null,
    "error": {
        "code": -32700,
        "message": "Parse error: Unexpected end of JSON input",
        "data": {
            "message": "Parse error: Unexpected end of JSON input"
        }
    }
}
```

## Environment
- OS: Ubuntu
- Kernel: Linux 6.8.0-48-generic amd64
- CPU: AMD Ryzen 5 PRO 4650U with Radeon Graphics
- Java Version: Ubuntu 11.0.24
- Blazegraph Version: 2.1.6-SNAPSHOT
- Memory: ~500MB free (freeMemory=501025240)

## Steps to Reproduce
1. Run examples/demo.py
2. Initial asset formatting succeeds:
   - Public assertion ID calculated: `0xe3a6...93cf`
   - Public assertion size: 299
   - Number of triples: 4
   - Number of chunks: 4
3. Error occurs during subsequent node info processing

## Expected Behavior
The demo should complete successfully without any JSON parse errors, properly processing both public and private assertions.

## Additional Context
- The node is running Blazegraph on http://172.17.0.1:9999
- Asset formatting appears successful before the error occurs
- The data structure shows both public and private assertions were properly formatted before the error

**Comment by NZT48** [comment]
Wrong repo, if this still persist you should open issue on [ot-node repository](https://github.com/OriginTrail/ot-node).
