### ISSUE TITLE
Can't send transactions with ParaChain

### ISSUE THREAD

**Issue by tjosm** [OriginTrail/neuroweb#40]
**Describe the bug**
I tried to transfer test OTP tokens within my wallets and the transaction is stuck on the status broadcast. I tried with and without KeepAlive option. But made no difference.

**To Reproduce**
1. Go to '[...](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Flofar.origin-trail.network#/accounts)'
2. Click on 'Send'
3. 'Try to send OTP tokens'
4. Transaction never completes

**Expected behavior**
Tokens are deposited to destination wallet.

**Comment by NZT48** [comment]
There was an issue on the Parachain devnet at that time, now you should be able to send tokens.
