### ISSUE TITLE
Uncaught error. e.call.metadata.metadataAtVersion is not a function (polkadot js apps)

### ISSUE THREAD

**Issue by AngryCryptocoiner** [OriginTrail/neuroweb#87]
**Describe the bug**
Uncaught error. e.call.metadata.metadataAtVersion is not a function at polkadot js org /settings/metadata

**To Reproduce**
It's very easy to reproduce. Just go to polkadot js org / apps and switch to Neuroweb and then go to settings -> metadata and you will see the error. I tried different browsers and got the same errror.

**Expected behavior**
I should see upgradable extensions and chain specifications

**Screenshots**

![2024-08-02_12-54-34](https://github.com/user-attachments/assets/be3933ba-d8ff-4248-95c8-9ef83e204fd3)

**Environment (please complete the following information):**
Web

**Additional context**
It seems to be on your side because other parachains unaffected.

**Comment by NZT48** [comment]
Thanks for reporting and opening issue on Polkadot-js repo. Looks like a thing on Polkadot-js app, as we did not change anything. Other issue: [polkadot-js/10802](https://github.com/polkadot-js/apps/issues/10802)

**Comment by AngryCryptocoiner** [comment]
> Thanks for reporting and opening issue on Polkadot-js repo. Looks like a thing on Polkadot-js app, as we did not change anything. Other issue: [polkadot-js/10802](https://github.com/polkadot-js/apps/issues/10802)

Seems like you haven't upgraded to v15 since API doesn't return metadataAtVersion. (This is just my assumption based a very shallow research)

**Comment by AngryCryptocoiner** [comment]
> Thanks for reporting and opening issue on Polkadot-js repo. Looks like a thing on Polkadot-js app, as we did not change anything. Other issue: [polkadot-js/10802](https://github.com/polkadot-js/apps/issues/10802)

I'm pretty confident it's not just polkadot js issue (you haven't implemented support for the new Ledger app ): https://dashboards.data.paritytech.io/metadata.html

**Comment by NZT48** [comment]
> > Thanks for reporting and opening issue on Polkadot-js repo. Looks like a thing on Polkadot-js app, as we did not change anything. Other issue: [polkadot-js/10802](https://github.com/polkadot-js/apps/issues/10802)
> 
> I'm pretty confident it's not just polkadot js issue (you haven't implemented support for the new Ledger app ): https://dashboards.data.paritytech.io/metadata.html

Thanks for the link, support for the new Ledger app is on our Testnet now, it is expected to reach Mainnet next week. We will check it then, also this issue does not exists on Testnet with new version: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-testnet-rpc.origin-trail.network%2F#/settings/metadata

**Comment by AngryCryptocoiner** [comment]
> > > Thanks for reporting and opening issue on Polkadot-js repo. Looks like a thing on Polkadot-js app, as we did not change anything. Other issue: [polkadot-js/10802](https://github.com/polkadot-js/apps/issues/10802)
> > 
> > 
> > I'm pretty confident it's not just polkadot js issue (you haven't implemented support for the new Ledger app ): https://dashboards.data.paritytech.io/metadata.html
> 
> Thanks for the link, support for the new Ledger app is on our Testnet now, it is expected to reach Mainnet next week. We will check it then, also this issue does not exists on Testnet with new version: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-testnet-rpc.origin-trail.network%2F#/settings/metadata

Is it live now?

**Comment by NZT48** [comment]
This is resolved now: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-rpc.origin-trail.network#/settings/metadata
